-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Tabla de usuarios
CREATE TABLE public.usuarios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mocha_user_id TEXT UNIQUE,
  auth_user_id UUID REFERENCES auth.users(id), -- Link to Supabase Auth
  nombre TEXT,
  apellido TEXT,
  email TEXT NOT NULL UNIQUE,
  rol TEXT NOT NULL CHECK (rol IN ('administrador', 'maestro')),
  is_active BOOLEAN DEFAULT true,
  password_hash TEXT, -- Legacy, can be removed if fully migrating to Supabase Auth
  session_token TEXT, -- Legacy
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_usuarios_email ON public.usuarios(email);
CREATE INDEX idx_usuarios_auth_user_id ON public.usuarios(auth_user_id);

-- Tabla de categorías de indicadores
CREATE TABLE public.categorias_indicadores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_categoria TEXT NOT NULL,
  descripcion TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tabla de estudiantes
CREATE TABLE public.estudiantes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  apellido TEXT NOT NULL,
  fecha_nacimiento DATE,
  grado_nivel TEXT,
  nivel_parvulo TEXT,
  id_curso_actual BIGINT REFERENCES public.cursos(id),
  nombre_tutor TEXT,
  telefono_tutor TEXT,
  email_tutor TEXT,
  direccion_tutor TEXT,
  genero TEXT,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_estudiantes_grado ON public.estudiantes(grado_nivel);
CREATE INDEX idx_estudiantes_apellido ON public.estudiantes(apellido);

-- Tabla de cursos
CREATE TABLE public.cursos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_curso TEXT NOT NULL,
  nivel TEXT NOT NULL,
  seccion TEXT,
  id_maestro BIGINT REFERENCES public.usuarios(id),
  descripcion TEXT,
  anio_escolar TEXT,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_cursos_nivel ON public.cursos(nivel);
CREATE INDEX idx_cursos_maestro ON public.cursos(id_maestro);

-- Tabla pivote: Estudiantes en Cursos
CREATE TABLE public.estudiantes_cursos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_estudiante BIGINT REFERENCES public.estudiantes(id),
  id_curso BIGINT REFERENCES public.cursos(id),
  fecha_inscripcion DATE DEFAULT CURRENT_DATE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_estudiantes_cursos_estudiante ON public.estudiantes_cursos(id_estudiante);
CREATE INDEX idx_estudiantes_cursos_curso ON public.estudiantes_cursos(id_curso);

-- Tabla de indicadores de evaluación
CREATE TABLE public.indicadores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descripcion TEXT NOT NULL,
  id_categoria BIGINT REFERENCES public.categorias_indicadores(id),
  niveles_aplicables TEXT,
  tipo_evaluacion TEXT,
  orden INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_indicadores_categoria ON public.indicadores(id_categoria);

-- Tabla de evaluaciones
CREATE TABLE public.evaluaciones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_estudiante BIGINT REFERENCES public.estudiantes(id),
  id_maestro BIGINT REFERENCES public.usuarios(id),
  id_indicador BIGINT REFERENCES public.indicadores(id),
  periodo_evaluacion TEXT NOT NULL,
  valor_evaluacion TEXT,
  comentario TEXT,
  estado TEXT DEFAULT 'borrador',
  fecha_evaluacion TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_evaluaciones_estudiante ON public.evaluaciones(id_estudiante);
CREATE INDEX idx_evaluaciones_maestro ON public.evaluaciones(id_maestro);
CREATE INDEX idx_evaluaciones_periodo ON public.evaluaciones(periodo_evaluacion);

-- Tabla de boletines generados
CREATE TABLE public.boletines_generados (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_estudiante BIGINT REFERENCES public.estudiantes(id),
  periodo_evaluacion TEXT NOT NULL,
  ruta_archivo_pdf TEXT,
  datos_json JSONB, -- Using JSONB for better performance
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_boletines_estudiante ON public.boletines_generados(id_estudiante);

-- Tabla de configuración del centro
CREATE TABLE public.configuracion_centro (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_centro TEXT,
  codigo_centro TEXT,
  direccion TEXT,
  telefono TEXT,
  email TEXT,
  regional TEXT,
  distrito TEXT,
  logo_minerd_url TEXT,
  logo_centro_url TEXT,
  director_nombre TEXT,
  anio_escolar_actual TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tabla de observaciones periódicas
CREATE TABLE public.observaciones_periodicas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_estudiante BIGINT REFERENCES public.estudiantes(id),
  id_maestro BIGINT REFERENCES public.usuarios(id),
  periodo_evaluacion TEXT NOT NULL,
  cualidades_destacar TEXT,
  necesita_apoyo TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_observaciones_estudiante_periodo ON public.observaciones_periodicas(id_estudiante, periodo_evaluacion);

-- Insert initial data
INSERT INTO public.configuracion_centro (nombre_centro, anio_escolar_actual) 
VALUES ('Centro Educativo', '2024-2025');

-- Note: We are NOT inserting the default admin user with a password hash here because we should create it via Supabase Auth.
-- However, to keep the app working if you manually create the user in Supabase Auth, you can insert a record here mapping the email.
