
-- Create table for notifications (avisos)
create table if not exists avisos_profesores (
  id bigint generated by default as identity primary key,
  titulo text not null,
  contenido text not null,
  target_rol text check (target_rol in ('all', 'maestro')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  created_by uuid references auth.users(id)
);

-- RLS
alter table avisos_profesores enable row level security;

-- Admins can insert/update/delete
create policy "Admins can manage avisos" 
  on avisos_profesores 
  for all 
  using (auth.uid() in (select auth_user_id from usuarios where rol = 'administrador'));

-- Everyone can read
create policy "Everyone can read avisos" 
  on avisos_profesores 
  for select 
  using (true);

-- Notificaciones de lectura (optional, keeping it simple for now, just global listing)
